name: mocap
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_database: ^10.2.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  get: ^4.6.5
  url_launcher: ^6.1.12
  image_picker: ^1.0.0

  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  firebase_remote_config: ^4.2.3
  flutter_downloader: ^1.10.5
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.7.2+3
  firebase_messaging: ^14.6.5
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"

flutter:
  assets:
    - assets/images/

  uses-material-design: true
