name: mocap
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  firebase_database: ^10.2.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  get: ^4.6.5
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  whatsapp: ^2.0.0
  image_picker: ^1.0.0

  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
